baseurl = "http://ryota-murakami.github.io/"
languageCode = "ja"
title = "ryota-murakami"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	page = "portfolio"
	name = "Ryota.Murakami"
	description = "Portfolio"

	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "thumbnail.jpeg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = '**<a href="https://twitter.com/malloc007" target="_blank">@Ryota.Murakami</a>**'

		# The icons will be shown if you enter your username
		hatenablog = "http://malloc.hatenablog.jp"
		twitter = "malloc007"
		github = "ryota-murakami"

		copyright = [
			"&copy; Ryota Murakami",
			"Design: [HTML5 UP](//html5up.net)",
			"Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		title = "The Straightforward Way"
		content = "I'm a web developer live in Tokyo, Japan. and “Hybrid Engineer”."

	[params.skills]
		title = "Skills"

		[[params.skills.items]]
			title = "JetBrains All Products Pack"

		[[params.skills.items]]
			title = "Software Test Knowledge. in order to verification App is not Broken. “Never”"

		[[params.skills.items]]
			title = "Software Architecture. Gof Design Patterns, Martin Fowler P of EAA: Service Layer etc.."

		[[params.skills.items]]
			title = "TCP/IP, Computer Science knowledges"

		[[params.skills.items]]
			title = "Git, Github Workflow"

		[[params.skills.items]]
			title = "HTML5, CSS3, Hugo"

		[[params.skills.items]]
			title = "SASS, Compass, BootStrap, Flat-UI, Materialize"

		[[params.skills.items]]
			title = "sketch(Mainly), Photoshop, Illustrator, Blender"

		[[params.skills.items]]
			title = "JavaScript(ES5, ES2015), React/Redux, jQuery, Angular1, Webpack, gulp"

		[[params.skills.items]]
			title = "ServiceWorker, WebComponent, WebSocket, WebGL, Web RTC, Canvas, Payment Request API, Apple Pay Safari"

		[[params.skills.items]]
			title = "PHP(Wordpress, Symfony, Laravel, Silex, Lumen, FuelPHP)"

		[[params.skills.items]]
			title = "Node.js, Express"

		[[params.skills.items]]
		 	title = "Ruby on Rails, Pure Ruby"

		[[params.skills.items]]
		 	title = "Python, scikit-learn, jupyter notebook"

		[[params.skills.items]]
		 	title = "Shell script, fish shell"

		[[params.skills.items]]
			title = "Debian Ubuntu(Mainly), Red Hat/CentOS, Kali Linux"

		[[params.skills.items]]
			title = "Let's Encrypt, onamae.com"

		[[params.skills.items]]
			title = "New Relic, Google Analytics, Google Search Console"

		[[params.skills.items]]
			title = "CLOUD VISION API, CLOUD NATURAL LANGUAGE API, CLOUD TRANSLATION API, (keras/tensorflow is I'v never touch. because google already provide powerful Machine-Lerned-Model, I'm satisfy use those inference.)"

		[[params.skills.items]]
			title = "MySQL, PostgreSQL, Elastic Search, RDS"

		[[params.skills.items]]
			title = "Nginx(Mainly), PHP-FPM, Apache, Unicorn, Puma"

		[[params.skills.items]]
			title = "Ansible, Vagrant, Docker, Kubernetes, Packer, fabric"

		[[params.skills.items]]
			title = "GCP(Mainly), AWS, IDCF Cloud"

		[[params.skills.items]]
			title = "Java, Scala, Apache Spark"

		[[params.skills.items]]
			title = "Android Progressive Web App"

		[[params.skills.items]]
			title = "iOS UIKit, Swift, Objective-C"

	[params.works]
		title = "Works"
		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.works.items]]
			url = "https://github.com/ryota-murakami/trueblue"
			title = "True Blue"
			description = "Archive tweets on every other day."

		[[params.works.items]]
			url = "https://github.com/ryota-murakami/twitter-bearer-token-getter"
			title = "Twitter bearer-token getter"
			description = "CLI tool of get twitter api bearer token."

		[[params.works.items]]
			url = "https://github.com/ryota-murakami/yamanote-bash"
			title = "Yamanote Bash"
			description = "yamanote-game in console."

		[[params.works.items]]
			url = "https://github.com/ryota-murakami/blog"
			title = "blog"
			description = "Personal blogs."

	[params.blogs]
		title = "Blogs"

			[[params.blogs.items]]
				url = "http://malloc.hatenablog.jp/"
				title = "Hatena Blog"
			[[params.blogs.items]]
				url = "https://malloc.tokyo/"
				title = "malloc.tokyo"

	[params.activity]
		title = "Activity"

			[[params.activity.items]]
				url = "https://twitter.com/malloc007"
				title = "Twitter"
			[[params.activity.items]]
				url = "https://www.instagram.com/ryota_murakam1/"
				title = "Instagram"
			[[params.activity.items]]
				url = "https://github.com/ryota-murakami"
				title = "GitHub"

	[params.contact]
		title = "Contact"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
		#
		# What you need to do for the setup?
		#
		# - set your email address under 'email' below
		# - upload the generated site to your server
		# - send a dummy email yourself to confirm your account
		# - click the confirm link in the email from www.formspree.io
		# - you're done. Happy mailing!
		email = "dojce1048@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"
