baseurl = "http://ryota-murakami.github.io/"
languageCode = "ja"
title = "ryota-murakami"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	page = "portfolio"
	name = "Ryota.Murakami"
	description = "Portfolio"

	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "thumbnail.jpeg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = '**<a href="https://twitter.com/malloc007" target="_blank">@Ryota.Murakami</a>**'

		# The icons will be shown if you enter your username
		hatenablog = "http://malloc.hatenablog.jp"
		twitter = "malloc007"
		github = "ryota-murakami"

		copyright = [
			"&copy; Ryota Murakami",
			"Design: [HTML5 UP](//html5up.net)",
			"Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		title = "A freelance Front End Developer."

		content = "I'm live in Tokyo, Japan.<br>who have been fascinated the JavaScript OSS community.üåé<br><br>I usually watch React issue/PR & discord community, and it's a my pleasure for as a programmers to contribute and grow through these communitiesüòÉ"

	[params.product]
		title = "Product"
		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.product.items]]
			url = "https://github.com/ryota-murakami/trueblue"
			title = "True Blue"
			description = "Archive tweets on every other day."

		[[params.product.items]]
			url = "https://github.com/ryota-murakami/clock-up"
			title = "Clock Up"
			description = "Attendance management tool for personal use."

	[params.blogs]
		title = "Blog"

			[[params.blogs.items]]
				url = "http://malloc.hatenablog.jp/"
				title = "Hatena Blog"

			[[params.blogs.items]]
				url = "https://qiita.com/ryota-murakami"
				title = "Qiita"

			[[params.blogs.items]]
				url = "https://malloc.tokyo"
				title = "malloc.tokyo"

	[params.sns]
		title = "SNS"

			[[params.sns.items]]
				url = "https://dev.to/ryotamurakami"
				title = "dev.to"

			[[params.sns.items]]
				url = "https://twitter.com/malloc007"
				title = "Twitter"

			[[params.sns.items]]
				url = "https://www.instagram.com/ryota_murakam1/"
				title = "Instagram"

			[[params.sns.items]]
				url = "https://www.facebook.com/ryota.murakami.100"
				title = "Facebook"

			[[params.sns.items]]
				url = "https://github.com/ryota-murakami"
				title = "GitHub"

		[params.skills]
				title = "skill set"

					[[params.skills.items]]
						title = "Software Test Knowledge. in order to verification App is not Broken. ‚ÄúNever‚Äù"

					[[params.skills.items]]
						title = "Software Architecture. Gof Design Patterns, Martin Fowler P of EAA: Service Layer etc.."

					[[params.skills.items]]
						title = "TCP/IP, Basics Computer Science knowledges"

					[[params.skills.items]]
						title = "Git, Github Workflow"

					[[params.skills.items]]
						title = "HTML5, CSS3, SASS, BootStrap, CSSinJS"

					[[params.skills.items]]
						title = "React, Redux, mobX, GraphQL, React Native"

					[[params.skills.items]]
						title = "JavaScript, jQuery, Angular1, Webpack, gulp"

					[[params.skills.items]]
						title = "ServiceWorker, Canvas, Payment Request API, Apple Pay Safari"

					[[params.skills.items]]
						title = "PHP(Wordpress, Symfony, Laravel, Silex, Lumen, FuelPHP)"

					[[params.skills.items]]
						title = "Node.js, Express"

					[[params.skills.items]]
					 	title = "Ruby on Rails, Pure Ruby"

					[[params.skills.items]]
					 	title = "Shell script, fish shell"

					[[params.skills.items]]
						title = "Debian Ubuntu, Red Hat/CentOS"

					[[params.skills.items]]
						title = "Let's Encrypt, onamae.com"

					[[params.skills.items]]
						title = "MySQL, PostgreSQL"

					[[params.skills.items]] title = "Nginx, PHP-FPM, Apache, Unicorn"

					[[params.skills.items]]
						title = "Ansible, Vagrant, Docker, Packer, fabric"

					[[params.skills.items]]
						title = "GCP(Mainly), AWS, IDCF Cloud"

					[[params.skills.items]]
						title = "Java, Scala, Apache Spark"

	[params.contact]
		title = "Contact"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
		#
		# What you need to do for the setup?
		#
		# - set your email address under 'email' below
		# - upload the generated site to your server
		# - send a dummy email yourself to confirm your account
		# - click the confirm link in the email from www.formspree.io
		# - you're done. Happy mailing!
		email = "dojce1048@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"
