baseurl = "http://ryota-murakami.github.io/"
languageCode = "ja"
title = "ryota-murakami"
theme = "hugo-strata-theme"

[params]
	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "Ryota.Murakami"
	description = "My Portfolio"

	# Enable Google Analytics by inserting your tracking code
	googleAnalytics = "UA-68130749-2"


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "thumbnail.jpeg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = '**<a href="https://twitter.com/malloc007" target="_blank">@Ryota.Murakami</a>**'

		# The icons will be shown if you enter your username
		hatenablog = "http://malloc.hatenablog.jp"
		twitter = "malloc007"
		github = "ryota-murakami"

		copyright = [
			"&copy; Ryota Murakami",
			"Design: [HTML5 UP](//html5up.net)",
			"Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		title = "Write Code Every day"
		content = "I'm a web developer in Tokyo in Japan. Interested Recently,<br>See the latest trends, data and visualizations from human community."

	[params.skills]
		title = "Skills"

		[[params.skills.items]]
			title = "Git, Github Workflow"

		[[params.skills.items]]
			title = "HTML5, CSS3, Hugo"

		[[params.skills.items]]
			title = "JavaScript(jQuery, Angular, React, Webpack eco-system)"

		[[params.skills.items]]
			title = "PHP(Wordpress, Symfony, Silex, FuelPHP)"

		[[params.skills.items]]
		 	title = "Ruby on Rails"

		[[params.skills.items]]
			title = "Linux(Ubuntu, CentOS)"

		[[params.skills.items]]
			title = "MySQL, PostgreSQL, Elastic Search"

		[[params.skills.items]]
			title = "Apache, nginx, Unicorn"

		[[params.skills.items]]
			title = "Ansible, Vagrant, Docker, Packer, fabric"

		[[params.skills.items]]
			title = "AWS, IDCF Cloud, Mackerel"

		[[params.skills.items]]
			title = "Java, Scala, Apache Spark"

		[[params.skills.items]]
			title = "Objective-C"

	[params.works]
		title = "Works"
		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.works.items]]
			url = "https://github.com/ryota-murakami/daily-tweet"
			title = "Daily Tweet"
			description = "Archive tweets on every other day."

		[[params.works.items]]
			url = "https://github.com/ryota-murakami/twitter-bearer-token-getter"
			title = "Twitter bearer-token getter"
			description = "CLI tool of get twitter api bearer token."

		[[params.works.items]]
			url = "https://github.com/ryota-murakami/yamanote-bash"
			title = "Yamanote Bash"
			description = "yamanote-game in console."

		[[params.works.items]]
			url = "https://github.com/ryota-murakami/blog"
			title = "blog"
			description = "Personal blogs."

	[params.activity]
		title = "Activity"

			[[params.activity.items]]
				url = "http://malloc.hatenablog.jp/"
				title = "Hatena Blog"
			[[params.activity.items]]
				url = "http://qiita.com/ryota-murakami"
				title = "Qiita"


	[params.contact]
		title = "Contact"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
		#
		# What you need to do for the setup?
		#
		# - set your email address under 'email' below
		# - upload the generated site to your server
		# - send a dummy email yourself to confirm your account
		# - click the confirm link in the email from www.formspree.io
		# - you're done. Happy mailing!
		email = "dojce1048@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"
